name: pre-commit

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      # Required for signing
      contents: write

    steps:
      # Checkout the code
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup Go
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      # Install golangci-lint
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0

      # Install tflint
      - run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | TFLINT_VERSION="v0.53.0" bash

      # Install terraform-docs
      - name: Install terraform-docs
        run: |
          mkdir -p $RUNNER_TEMP/terraform-docs-temp
          cd $RUNNER_TEMP/terraform-docs-temp
          curl -sSL https://terraform-docs.io/dl/v0.19.0/terraform-docs-v0.19.0-$(uname)-amd64.tar.gz -o terraform-docs.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          mkdir -p $HOME/bin
          mv terraform-docs $HOME/bin/terraform-docs
          cd -
          echo "$HOME/bin" >> $GITHUB_PATH

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: |
            .pre-commit-config.yaml

      # Install Checkov
      - name: Install Checkov
        run: python -m pip install checkov==3.2.257

      # Setup OpenTofu
      - uses: opentofu/setup-opentofu@v1

      # Cache pre-commit hooks to prevent recreating hook environments each time
      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      # Run pre-commit
      - uses: pre-commit/action@v3.0.1
        id: pre-commit
        # If this is a Renovate PR, continue on error to allow auto-fixing
        continue-on-error: ${{ contains(github.head_ref, 'renovate') }}
        with:
          extra_args: --all-files --show-diff-on-failure

      - name: Commit pre-commit changes if Renovate PR
        if: |
          contains(github.head_ref, 'renovate') &&
          steps.pre-commit.outcome == 'failure' &&
          github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global commit.gpgsign true
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -S -m "style: auto-fix pre-commit issues"
            git push
          fi
