name: pre-commit

on:
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      # Required for signing
      contents: write
    outputs:
      is_renovate: ${{ contains(github.head_ref, 'renovate') }}
      pre_commit_status: ${{ steps.pre-commit.outcome }}
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup Go
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      # Install golangci-lint
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0

      # Install tflint
      - run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | TFLINT_VERSION="v0.53.0" bash

      # Install terraform-docs
      - name: Install terraform-docs
        run: |
          mkdir -p $RUNNER_TEMP/terraform-docs-temp
          cd $RUNNER_TEMP/terraform-docs-temp
          curl -sSL https://terraform-docs.io/dl/v0.19.0/terraform-docs-v0.19.0-$(uname)-amd64.tar.gz -o terraform-docs.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          mkdir -p $HOME/bin
          mv terraform-docs $HOME/bin/terraform-docs
          cd -
          echo "$HOME/bin" >> $GITHUB_PATH

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: |
            .pre-commit-config.yaml

      # Install Checkov
      - name: Install Checkov
        run: python -m pip install checkov==3.2.257

      # Setup OpenTofu
      - uses: opentofu/setup-opentofu@v1

      # Cache pre-commit hooks to prevent recreating hook environments each time
      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      # Run pre-commit
      - uses: pre-commit/action@v3.0.1
        id: pre-commit
        # If this is a Renovate PR, continue on error to allow auto-fixing
        continue-on-error: ${{ contains(github.head_ref, 'renovate') }}
        with:
          extra_args: --all-files --show-diff-on-failure

      # Commit pre-commit changes if Renovate PR
      - uses: planetscale/ghcommit-action@v0.1.6
        if: |
          contains(github.head_ref, 'renovate') &&
          steps.pre-commit.outcome == 'failure' &&
          github.event_name == 'pull_request'
        with:
          commit_message: "style: auto-fix pre-commit issues"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Output job results
        run: |
          echo "Is Renovate PR: ${{ contains(github.head_ref, 'renovate') }}"
          echo "Pre-commit status: ${{ steps.pre-commit.outcome }}"

  call-terratest-workflow:
    needs: pre-commit
    permissions:
      id-token: write
      contents: read
    if: |
      needs.pre-commit.outputs.is_renovate == 'true' &&
      (needs.pre-commit.outputs.pre_commit_status == 'success' ||
       needs.pre-commit.result == 'success')
    uses: ./.github/workflows/terratest.yml
