name: pre-commit

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Go
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      # Install golangci-lint
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0

      # Install tflint
      - run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | TFLINT_VERSION="v0.53.0" bash

      # Install terraform-docs
      - name: Install terraform-docs
        run: |
          mkdir -p $RUNNER_TEMP/terraform-docs-temp
          cd $RUNNER_TEMP/terraform-docs-temp
          curl -sSL https://terraform-docs.io/dl/v0.19.0/terraform-docs-v0.19.0-$(uname)-amd64.tar.gz -o terraform-docs.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          mkdir -p $HOME/bin
          mv terraform-docs $HOME/bin/terraform-docs
          cd -
          echo "$HOME/bin" >> $GITHUB_PATH

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: |
            .pre-commit-config.yaml

      # Install Checkov
      - name: Install Checkov
        run: python -m pip install checkov==3.2.257

      # Setup OpenTofu
      - uses: opentofu/setup-opentofu@v1

      # Cache pre-commit hooks to prevent recreating hook environments each time
      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      # Run pre-commit
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --show-diff-on-failure
