name: Terratest on AWS

on:
  workflow_dispatch:
  pull_request:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  terratest:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'workflow_call' ||
      contains(github.event.head_commit.message, '/run-e2e')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Configure AWS credentials from OIDC
      #   uses: aws-actions/configure-aws-credentials@v3
      #   with:
      #     role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/<YOUR_ROLE_NAME>
      #     aws-region: us-east-1

      - name: Set up Go with built-in caching
        uses: actions/setup-go@v5
        with:
          cache: true # Caching is enabled by default

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Install Go dependencies
        run: go mod tidy
        working-directory: "./test"

      - name: Run Terratest
        run: go test -v
        working-directory: "./test"
