name: Validate Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      # Required for signing
      contents: write
    outputs:
      is_renovate: ${{ contains(github.head_ref, 'renovate') }}
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup Go
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      # Install golangci-lint
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0

      # Install tflint
      - run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | TFLINT_VERSION="v0.53.0" bash

      # Install terraform-docs
      - name: Install terraform-docs
        run: |
          mkdir -p $RUNNER_TEMP/terraform-docs-temp
          cd $RUNNER_TEMP/terraform-docs-temp
          curl -sSL https://terraform-docs.io/dl/v0.19.0/terraform-docs-v0.19.0-$(uname)-amd64.tar.gz -o terraform-docs.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          mkdir -p $HOME/bin
          mv terraform-docs $HOME/bin/terraform-docs
          cd -
          echo "$HOME/bin" >> $GITHUB_PATH

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: |
            .pre-commit-config.yaml

      # Install Checkov
      - name: Install Checkov
        run: python -m pip install checkov==3.2.257

      # Setup OpenTofu
      - uses: opentofu/setup-opentofu@v1

      # Cache pre-commit hooks to prevent recreating hook environments each time
      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      # Run pre-commit
      - uses: pre-commit/action@v3.0.1
        id: pre-commit
        # If this is a Renovate PR, continue on error to allow auto-fixing
        continue-on-error: ${{ contains(github.head_ref, 'renovate') }}
        with:
          extra_args: --all-files --show-diff-on-failure

      # Commit pre-commit changes if Renovate PR
      - uses: planetscale/ghcommit-action@v0.1.6
        if: |
          contains(github.head_ref, 'renovate') &&
          steps.pre-commit.outcome == 'failure' &&
          github.event_name == 'pull_request'
        with:
          commit_message: "style: auto-fix pre-commit issues"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  terratest:
    needs: pre-commit
    # if: |
    #   github.event_name == 'workflow_dispatch' ||
    #   contains(github.event.head_commit.message, '/run-e2e') ||
    #   github.event.workflow_call != null
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # - name: Configure AWS credentials from OIDC
      #   uses: aws-actions/configure-aws-credentials@v3
      #   with:
      #     role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/<YOUR_ROLE_NAME>
      #     aws-region: us-east-1

      - name: Set up Go with built-in caching
        uses: actions/setup-go@v5
        with:
          cache: true # Caching is enabled by default

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Install Go dependencies
        run: go mod tidy
        working-directory: "./test"

      - name: Run Terratest
        run: go test -v
        working-directory: "./test"
